name: build and deploy to ECR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven & generate soanr report
      run: mvn -B package --file pom.xml
    - name: sonar report 
      run: mvn sonar:sonar --file pom.xml -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_URL:  ${{ secrets.SONAR_URL }}
    #- name: docker build
     # run: |
      #  ls .
      # pwd
      #  tree .
        #sudo apt-get update -y && sudo apt-get install trivy -y
        #docker build -t kesav38/mvn_image:${{ github.sha }} . 
        #trivy image  kesav38/mvn_image:${{ github.sha }}
      #  docker login -u $Username -p $passwd
      #  docker push kesav38/mvn_image:${{ github.sha }}
      #env: 
       # Username: ${{ secrets.DOCKER_USERNAME }}  #docker credentials to push to docker registry
       # passwd: ${{ secrets.DOCKER_PASSWD }}
    - name: docker build 
      run: |
        docker build -t ${{secrets.ECR_REPO_URL}}:${{ github.sha }}  .
        aws configure AWS Access Key ID:${{secrets.ACCESS_KEY}}  AWS Secret Access Key:${{secrets.SECRET_KEY}}
